AWSTemplateFormatVersion: "2010-09-09"
Resources:
     MyEC2Instance:
       Type: 'AWS::EC2::Instance'
       Properties:
         InstanceType: t2.micro
         ImageId: ami-08a0d1e16fc3f61ea
     Mys3Bucket:
       Type: 'AWS::S3::Bucket'
       Properties:
            BucketName: springapp-bucket
     MyRDSInstance:
       Type: 'AWS::RDS::DBInstance'
       Properties:
            DBInstanceClass: db.t2.micro
            Engine: mysql
            MasterUsername: admin 
            MasterUserPassword: root 
            AllocatedStorage: 20
                         
